server:
  port: 8000
  error:
    include-binding-errors: always
    include-message: always

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka # 다른걸로 ??
#    enabled: true
#  instance:
#    instance-id: ${spring.application.name}:${random.value}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: batch
          predicates:
            - Path=/batch/**
          filters:
            - StripPrefix=1
          uri: lb://batch
        - id: employee
          predicates:
            - Path=/employee/**
          filters:
            - StripPrefix=1
          uri: lb://employee
        - id: login
          predicates:
            - Path=/login/**
          filters:
            - StripPrefix=1
          uri: lb://login
        - id: salary
          predicates:
            - Path=/salary/**
          filters:
            - StripPrefix=1
          uri: lb://salary
        - id: total
          predicates:
            - Path=/total/**
          filters:
            - StripPrefix=1
          uri: lb://total
      default-filters:
        - name: JwtGlobalFilter
          args:
            baseMessage: gateway filter
            preLogger: true
            postLogger: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allow-credentials: true
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
jwt:
  secretKey: ${JWT_SECRETKEY}
