apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: batch
  template:
    metadata:
      labels:
        app: batch
    spec:
      containers:
        - name: batch-backend
          image: 533267394261.dkr.ecr.ap-northeast-2.amazonaws.com/harbor-employee:latest
          ports:
            - containerPort: 8005

          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "250Mi"
          ##### Kubectl secrets #####
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: DB_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: batch-service #ingress admin name과 동일해야 한다.
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8005 # admin service port
  selector:
    app: batch