apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee-backend
          image: 533267394261.dkr.ecr.ap-northeast-2.amazonaws.com/harbor-employee:latest
          ports:
            - containerPort: 8004

          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "250Mi"
          ##### Kubectl secrets #####
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: DB_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: REDIS_HOST
            - name: JWT_SECRETEKEY
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: JWT_SECRETEKEY
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: HOST
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: employee-service #ingress admin name과 동일해야 한다.
#spec:
#  type: ClusterIP
#  ports:
#    - name: http
#      port: 80
#      targetPort: 8004 # admin service port
#  selector:
#    app: employee