server:
  port: 8005
spring:
  application:
    name: batch
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #    url: jdbc:mariadb://som_db/som?allowPublicKeyRetrieval=true&useSSL=false
    url: jdbc:mariadb://${DB_HOST}:3306/harbor_employee
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update #update
    show-sql: true

  batch:
    #    job:
    #      names: ${job.name:NONE}
    jdbc:
      initialize-schema: ALWAYS
