server:
  port: 8004
spring:
  application:
    name: employee
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cbku8mggudio.ap-northeast-2.rds.amazonaws.com:3306/harbor_employee
    username: admin
    password: harbor123
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
    show-sql: true
  redis:
    host: redis-test-1.c5w28v.ng.0001.apn2.cache.amazonaws.com
    port: 6379
  # eureka ??? ?? name?? ??? ?? ??.
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
logging:
  level:
    root: info
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
jwt:
  secretKey: CE254B51A873FD7C90C9338C534787FFCDEA4DC217B49AF2CB7DA54661418349
url: "http://localhost:8000"