cloud:
  aws:
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY} # IAM 사용자 엑세스 키
      secretKey: ${AWS_S3_SECRET_KEY} # IAM 사용자 비밀 엑세스 키
    s3:
      bucket: harborfilebucket # 버킷명
    region:
      static: ap-northeast-2 # 리전
    stack:
      auto: true # Spring Cloud는 환경 또는 스택을 기반으로 이를 자동으로 감지