spring:
  profiles:
    group:
      "local" : "local, mail"
    active : local
---
server:
  port: 8001
spring:
  application:
    name: login
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/harbor_login
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  # eureka ??? ?? name?? ??? ?? ??.
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
logging:
  level:
    root: info
    com.example.harbor_login.client: DEBUG
jwt:
  expiration: 30
  secretKey: ${{ secrets.JWT_SECRETEKEY }}

url: "http://localhost:8000"