spring:
  profiles:
    group:
      "local" : "local, mail, s3"
    active : local
---
server:
  port: 8001
spring:
  application:
    name: login
  servlet:
    multipart:
      enabled: true
      location: C:/HARBOR/
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 1MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cbku8mggudio.ap-northeast-2.rds.amazonaws.com:3306/harbor_login
    username: admin
    password: harbor123
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  # eureka ??? ?? name?? ??? ?? ??.
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
logging:
  level:
    root: info
    com.example.harbor_login.client: DEBUG
jwt:
  expiration: 30
  secretKey: CE254B51A873FD7C90C9338C534787FFCDEA4DC217B49AF2CB7DA54661418349

url: "http://localhost:8000"