server:
  port: 8003
spring:
  application:
    name: total
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}/harbor_total
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
    show-sql: true
  # eureka ??? ?? name?? ??? ?? ??.
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
logging:
  level:
    root: info
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
jwt:
  expiration: 30
  secretKey: ${JWT_SECRETKEY}
url: "http://localhost:8000"