server:
  port: 8002
spring:
  application:
    name: salary
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}/harbor_salary
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  # eureka ??? ?? name?? ??? ?? ??.
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
logging:
  level:
    root: info
    com.example.harbor_login.client: DEBUG
jwt:
  secretKey: ${JWT_SECRETKEY}

url: "http://localhost:8000"